### ISSUE TITLE
Ubuntu 中文显示问题

### ISSUE THREAD

**Issue by dickens7** [biyidev/biyi#55]
声明自定义字体 `Roboto`, Flutter 在 Linux 先默认使用的是  Roboto 字体

> `pubspec.yaml` 

```yaml
...
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/DroidSansFallbackFull.ttf
...
```

- 使用自定义字体后仍有部分，中文显示不正常。

![image](https://user-images.githubusercontent.com/41516298/149867920-256b670b-9810-48d3-b19a-be0b46e577bb.png)

此处的 `翻译` `清空` 按钮以及 placeholder 仍然为乱码 debug 发现这里使用的字体为 `.SF Pro Text` 

> `pubspec.yaml` 

```yaml

...
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/DroidSansFallbackFull.ttf
    - family: .SF Pro Text
      fonts:
        - asset: assets/fonts/DroidSansFallbackFull.ttf 
...
```
零时增加字体可以解决。

![image](https://user-images.githubusercontent.com/41516298/149883012-3e360eb1-7ad3-459a-9036-b60f607825e8.png)

- 这时设置的  `CustomAppBar.title` 仍然有问题

![image](https://user-images.githubusercontent.com/41516298/149867948-001b1277-c1f0-48f6-a5ce-eff3f55b3095.png)
